#!/bin/sh

set -e

case "$1" in
    configure|triggered)
        if which systemctl >/dev/null 2>&1
        then
            echo "Reloading systemd"
            systemctl enable ubuntu-system-adjustments.service
            systemctl daemon-reload || true
        fi

        update-alternatives \
            --install /usr/share/plymouth/themes/default.plymouth default.plymouth \
            /usr/share/plymouth/themes/mint-logo/mint-logo.plymouth 200

        update-alternatives \
            --install /usr/share/plymouth/themes/text.plymouth text.plymouth \
            /usr/share/plymouth/themes/mint-text/mint-text.plymouth 200

        /usr/share/ubuntu-system-adjustments/systemd/start || true

        if [ -f /etc/systemd/system/hddtemp.service ]; then
            echo "Remove obsolete file /etc/systemd/system/hddtemp.service"
            rm -f /etc/systemd/system/hddtemp.service
        fi
    ;;
    abort-upgrade|abort-remove|abort-deconfigure)

    ;;
    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0


