#!/bin/sh

set -e

case "$1" in
	purge|remove)
		update-alternatives \
			--remove default.plymouth /usr/share/plymouth/themes/bodhi-boss/bodhi-boss.plymouth
		
		if which update-initramfs >/dev/null 2>&1
		then
			update-initramfs -u
		fi
		;;
esac
